backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'docs: create {{collection}} “{{slug}}”'
    update: 'docs: update {{collection}} “{{slug}}”'
    delete: 'docs: delete {{collection}} “{{slug}}”'
    uploadMedia: 'docs: upload “{{path}}”'
    deleteMedia: 'docs: delete “{{path}}”'
    openAuthoring: 'docs: {{message}}'
local_backend: true
publish_mode: editorial_workflow
media_folder: '/public/uploads'
public_folder: '/uploads'
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_content/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
